import vine, { SimpleMessagesProvider } from '@vinejs/vine'


const mensagens = {
    required: 'O campo {{ field }} é obrigatório',
    number: 'O campo {{ field }} deve ser um número',
    min: 'O campo {{ field }} deve ter no mínimo {{ min }}',
    max: 'O campo {{ field }} não deve ser maior que {{ max }}',
    range: 'O campo {{ field }} deve estar entre {{ min }} e {{ max }}',
    positive: 'O campo {{ field }} deve ser positivo',
    negative: 'O campo {{ field }} deve ser negativo',
    decimal: 'O campo {{ field }} deve ter {{ digits }} casas decimais',
    withoutDecimals: 'O campo {{ field }} não deve ter casas decimais',
    string: 'O campo {{ field }} deve ser uma string',
    email: 'O campo {{ field }} deve ser um endereço de e-mail válido',
    regex: 'O formato do campo {{ field }} é inválido',
    url: 'O campo {{ field }} deve ser uma URL válida',
    activeUrl: 'O campo {{ field }} deve ser uma URL válida',
    alpha: 'O campo {{ field }} deve conter apenas letras',
    alphaNumeric: 'O campo {{ field }} deve conter apenas letras e números',
    minLength: 'O campo {{ field }} deve ter pelo menos {{ min }} caracteres',
    maxLength: 'O campo {{ field }} não deve ter mais que {{ max }} caracteres',
    fixedLength: 'O campo {{ field }} deve ter {{ size }} caracteres de comprimento',
    confirmed: 'O campo {{ field }} e o campo {{ otherField }} devem ser iguais',
    endsWith: 'O campo {{ field }} deve terminar com {{ substring }}',
    startsWith: 'O campo {{ field }} deve começar com {{ substring }}',
    sameAs: 'O campo {{ field }} e o campo {{ otherField }} devem ser iguais',
    notSameAs: 'O campo {{ field }} e o campo {{ otherField }} devem ser diferentes',
    in: 'O {{ field }} selecionado é inválido',
    notIn: 'O {{ field }} selecionado é inválido',
    ipAddress: 'O campo {{ field }} deve ser um endereço IP válido',
    uuid: 'O campo {{ field }} deve ser um UUID válido',
    ascii: 'O campo {{ field }} deve conter apenas caracteres ASCII',
    creditCard: 'O campo {{ field }} deve ser um número de cartão de crédito válido para {{ providersList }}',
    hexCode: 'O campo {{ field }} deve ser um código de cor hexadecimal válido',
    iban: 'O campo {{ field }} deve ser um número IBAN válido',
    jwt: 'O campo {{ field }} deve ser um token JWT válido',
    coordinates: 'O campo {{ field }} deve conter coordenadas de latitude e longitude',
    mobile: 'O campo {{ field }} deve ser um número de celular válido',
    passport: 'O campo {{ field }} deve ser um número de passaporte válido',
    postalCode: 'O campo {{ field }} deve ser um código postal válido',
    date: 'O campo {{ field }} deve ser um valor de data e hora',
    'date.equals': 'O campo {{ field }} deve ser uma data igual a {{ expectedValue }}',
    'date.after': 'O campo {{ field }} deve ser uma data posterior a {{ expectedValue }}',
    'date.before': 'O campo {{ field }} deve ser uma data anterior a {{ expectedValue }}',
    'date.afterOrEqual': 'O campo {{ field }} deve ser uma data posterior ou igual a {{ expectedValue }}',
    'date.beforeOrEqual': 'O campo {{ field }} deve ser uma data anterior ou igual a {{ expectedValue }}',

    'date.sameAs': 'O campo {{ field }} e o campo {{ otherField }} devem ser iguais',
    'date.notSameAs': 'O campo {{ field }} e o campo {{ otherField }} devem ser diferentes',
    'date.afterField': 'O campo {{ field }} deve ser uma data posterior ao campo {{ otherField }}',
}

vine.messagesProvider = new SimpleMessagesProvider(mensagens)